all: clean switch_column dir_stat oz_demo

switch_column:
	gcc -std=gnu99 switch_column.c -o switch_column

dir_stat:
	gcc -std=gnu99 dir_stat.c -o dir_stat

oz_demo:
	gcc -std=gnu99  oz_demo.c -o oz_demo

clean:
	rm -f switch_column dir_stat oz_demo