all: clean switch_column dir_stat oz_demo

switch_column:
	gcc -c switch_column.c -o switch_column

dir_stat:
	gcc -c dir_stat.c -o dir_stat

oz_demo:
	gcc -c oz_demo.c -o oz_demo

clean:
	rm -f switch_column dir_stat oz_demo